config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :lists do
    resources :comments, only: [:create, :destroy]
  end
  get 'goods/search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_one_attached :list_image

   with_options presence: true do
    validates :title
    validates :body
  end

  def get_list_image(width, height)
  unless list_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    list_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    list_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @comment = Comment.new(comment_params)
    @comment.list_id = @list.id
    @comments = @list.comments.order(created_at: 'DESC').page(params[:page]).per(5)
    @comment.save
  end

  def destroy
    @list = List.find(params[:list_id])
    Comment.find(params[:id]).destroy
    @comments = @list.comments.order(created_at: 'DESC').page(params[:page]).per(5)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :name)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def search
    if params[:keyword]
      @goods = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    end
    @outdoors_goods = RakutenWebService::Ichiba::Item.search(keyword: "登山調理")
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def index
    puts "作成したキー#{ENV['SECRET_KEY']}"
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @comment = Comment.new
    @comments = @list.comments.order(created_at: 'DESC').page(params[:page]).per(5)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to "/lists"
  end

  private

  def list_params
    params.require(:list).permit(:title, :body, :list_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/comments/_comment_form.html.erb
<%= form_with model: comment, url: list_comments_path(@list), method: :post, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, rows: "2", placeholder: "コメントはこちら" ,class: "form-control"%>
    <%= f.text_field :name, placeholder: "お名前" ,class: "form-control w-25 mt-3" %>
  </div>
  <div class="form-group text-right">
    <%= f.submit "送信",class: "btn btn-sm btn-blue" %>
  </div>
<%end%>

app/views/comments/_comment_list.html.erb
<% comments.each do |comment| %>
  <table class="table table-borderless">
    <tbody>
      <tr class="row d-flex align-items-center">
        <td class="col-7 col-md-7 col-lg-9"><%= comment.comment %></td>
        <td class="col-3 col-md-3 col-lg-2 text-muted"><%= comment.name %></td>
        <td class="col-2 col-md-2 col-lg-1">
          <%= link_to "削除",list_comment_path(comment.list, comment),"data-confirm"=>"本当に消しますか？", method: :delete,class: "btn btn-danger" %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/comments/create.js.erb
$('#comment_comment').val("");
$('#comment_list').html("<%= j(render"comments/comment_list",comments: @comments) %>");

app/views/comments/destroy.js.erb
$('#comment_list').html("<%= j(render"comments/comment_list",comments: @comments) %>");
<% if @comments.count <= 0 %>
  $('#comment_list').html('<p class="ml-5 my-5">〜コメントはありません〜</p>')
<% end %>

app/views/goods/search.html.erb
<%= form_with url: goods_search_path,method: :get do |f|%>
  <%= f.text_field :keyword %>
  <%= f.submit '検索' %>
<% end %>

<% if @goods.present? %>
  <% @goods.each do |goods| %>
    <li>
      <%= link_to goods.url do %>
        <%= image_tag (goods.medium_image_urls[0]) %>
      <% end %>
      <%= goods.name %>
    </li>
  <% end %>
<% else %>
  <% @outdoors_goods.each do |outdoors_goods| %>
  <li>
    <%= link_to outdoors_goods.url do %>
      <%= image_tag (outdoors_goods.medium_image_urls[0]) %>
      <%= outdoors_goods.name %>
    <% end %>
  </li>
  <% end %>
<% end %>

app/views/homes/top.html.erb
<div class="design-container">
  <div class="container">
    <div class="row">
      <div class="col mx-auto text-center top-text">
        <h1 class="my-5">Hello!<br>Welcome to this App!</h1>
        <p>こんにちは！</p>
        <p>これは画像も投稿できるブログアプリです。</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<%if obj.errors.any?%>
 <%= obj.errors.count %>件のエラーが発生しました
   <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer></footer>

app/views/layouts/_header.html.erb
<header>
  <h3 class="pt-4 text-center">
    <%= link_to "Practise App", root_path, class: "title" %>
  </h3>
  <nav>
    <ul class="nav-list">
      <%if user_signed_in?%>
        <li class="nav-list-item">
          <%= link_to "Top", root_path, class: "nav-item" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path, class: "nav-item" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path, class: "nav-item" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-item" %>
        </li>
      <% else %>
        <li class="nav-list-item">
          <%= link_to "Top", root_path, class: "nav-item" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path, class: "nav-item" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto">
      <h3 class="new-post text-center mt-5">投稿編集</h3>
        <%= render "layouts/error", obj: @list %>
        <div class="new-post">
          <%= form_with model: @list, url: list_path,method: :patch, local: true do |f| %>
           <div class="form-group">
            <%= f.label:タイトル %>
            <%= f.text_field :title, class: "new-form form-control" %>
           </div>
           <div class="form-group">
            <%= f.label:本文 %>
            <%= f.text_area :body, class: "new-form form-control" %>
           </div>
           <div class="form-group">
            <%= f.label:画像 %><br>
            <%= f.file_field :list_image,accept: "image/*" %>
           </div>
           <div class="form-group text-center my-5">
            <%= f.submit "更新", class: "btn btn-blue" %>
           </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="design-container">
 <div class="container">
  <div class="card-list-container py-3">
   <div class="row">
     <% @lists.each do |list| %>
      <div class="col-sm-9 offset-sm-2 col-md-6 offset-md-0 col-lg-4 offset-lg-0">
       <div class="card-link my-3">
        <div class="card list-box my-3 mx-2">
         <%= link_to list_path(list.id) do %>
          <%= image_tag list.get_list_image(1000,1000),class: "card-img" %>
          <div class="card-body">
            <span class="text-muted small"><%= list.created_at.strftime('%Y/%m/%d') %></span>
            <h5 class="card-title"><%= list.title %></h5>
            <p class="card-text"><%= list.body %></p>
          </div>
         <% end %>
        </div>
       </div>
      </div>
     <%end%>
    </div>
   </div>
 </div>
</div>

app/views/lists/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-10 col-lg-8 mx-auto">
   <h3 class="new-post text-center mt-5">新規投稿</h3>
    <%= render "layouts/error", obj: @list %>
     <div class="new-post">
      <%= form_with model: @list, url: lists_path,method: :post, local: true do |f| %>
       <div class="form-group">
        <%= f.label:タイトル %>
        <%= f.text_field :title, class: "new-form form-control" %>
       </div>
       <div class="form-group">
        <%= f.label:本文 %>
        <%= f.text_area :body, class: "new-form form-control" %>
       </div>
       <div class="form-group">
        <%= f.label:画像 %><br>
        <%= f.file_field :list_image,accept: "image/*" %>
       </div>
       <div class="form-group text-center my-5">
        <%= f.submit"投稿", class: "btn btn-blue" %>
       </div>
      <% end %>
     </div>
  </div>
 </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto">
      <h4 class="text-center mt-5">「<%= @list.title %>」</h4>
      <div class="text-center">
        <%= image_tag @list.get_list_image(300,300),class: "show-image my-3" %>
      </div>
      <h5 class="text-center"><%= @list.body %></h5>

      <% if user_signed_in? %>
        <div class="text-center my-5">
          <%= link_to edit_list_path(@list),class: "btn btn-success mr-2" do %>
            編集
          <% end %>
          <%= link_to list_path(@list),method: :delete,"data-confirm"=>"本当に削除しますか？",class: "btn btn-danger" do %>
            削除
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto">
      <p class="comment-heading">コメント</p>
        <div id="comment_list">
          <% if @list.comments.present? %>
            <%= render"comments/comment_list", comments: @comments %>
          <% else %>
            <p class="ml-5 my-5">〜コメントはありません〜</p>
          <% end %>
        </div>
        <div class="row my-3">
          <div class="mx-auto"><%= paginate @comments %></div>
        </div>
        <div class="row">
          <div class="col">
            <%= render"comments/comment_form", comment: @comment %>
          </div>
        </div>
    </div>
  </div>
</div>